### ISSUE TITLE
How to setup the D1-mini to listen on the correct topic?

### ISSUE THREAD

**Issue by pornstrup** [IntranetOfThings/wemos-garage#2]
Sorry for all my questions. How do you define where your D1 mini listens for mqtt message? I got it all running on openhab with the mosquitto broker. With mqtt.fx I can subscribe to /homie/wemos-01/opener/press/set and see the "1" message, but the D1-mini does not see the message as it doesn´t switch on the relay. So how do I define the D1-mini to listen on /homie/wemos-01/opener/press/set?

**Comment by pornstrup** [comment]
And the sensor on pin D5 what kind of sensor is that?

**Comment by sumnerboy12** [comment]
Read the Homie documentation for details on topic structure. The sensor is a simple reed switch.
